-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.37-MariaDB - Source distribution
-- Server OS:                    Linux
-- HeidiSQL Version:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table SKRIPSIGIS.ADMIN
CREATE TABLE IF NOT EXISTS `ADMIN` (
  `ADMIN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADMIN_USERNAME` varchar(50) DEFAULT NULL,
  `ADMIN_PASSWORD` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ADMIN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Dumping data for table SKRIPSIGIS.ADMIN: ~2 rows (approximately)
/*!40000 ALTER TABLE `ADMIN` DISABLE KEYS */;
INSERT INTO `ADMIN` (`ADMIN_ID`, `ADMIN_USERNAME`, `ADMIN_PASSWORD`) VALUES
	(1, 'admin', 'admin'),
	(2, 'pengurus', 'pengurus');
/*!40000 ALTER TABLE `ADMIN` ENABLE KEYS */;

-- Dumping structure for table SKRIPSIGIS.GURU
CREATE TABLE IF NOT EXISTS `GURU` (
  `GURU_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GURU_USERNAME` varchar(50) DEFAULT NULL,
  `GURU_PASSWORD` varchar(50) DEFAULT NULL,
  `GURU_NAMA` varchar(50) DEFAULT NULL,
  `GURU_NIP` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`GURU_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

-- Dumping data for table SKRIPSIGIS.GURU: ~3 rows (approximately)
/*!40000 ALTER TABLE `GURU` DISABLE KEYS */;
INSERT INTO `GURU` (`GURU_ID`, `GURU_USERNAME`, `GURU_PASSWORD`, `GURU_NAMA`, `GURU_NIP`) VALUES
	(4, '1', '1', 'HIDAYAT', '1'),
	(5, '1', '1', 'FIKRI HIDAYAT', '1'),
	(6, '12', '12', 'hidayat fikri', '12');
/*!40000 ALTER TABLE `GURU` ENABLE KEYS */;

-- Dumping structure for table SKRIPSIGIS.JURUSAN
CREATE TABLE IF NOT EXISTS `JURUSAN` (
  `JURUSAN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `JURUSAN` text,
  `JURUSAN_WARNA` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`JURUSAN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- Dumping data for table SKRIPSIGIS.JURUSAN: ~2 rows (approximately)
/*!40000 ALTER TABLE `JURUSAN` DISABLE KEYS */;
INSERT INTO `JURUSAN` (`JURUSAN_ID`, `JURUSAN`, `JURUSAN_WARNA`) VALUES
	(3, 'TEKNIK INFORMATIKA', '#753333'),
	(5, 'TEKNIK ELEKTRO', '#28ed08');
/*!40000 ALTER TABLE `JURUSAN` ENABLE KEYS */;

-- Dumping structure for table SKRIPSIGIS.LAPORAN
CREATE TABLE IF NOT EXISTS `LAPORAN` (
  `LAPORAN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SISWA_ID` int(11) NOT NULL,
  `LOCATION_ID` int(11) DEFAULT NULL,
  `LAPORAN_TANGGAL` date NOT NULL,
  `LAPORAN_PENANGGUNG_JAWAB` varchar(50) NOT NULL,
  `LAPORAN` text NOT NULL,
  `LAPORAN_STATUS` varchar(50) NOT NULL,
  PRIMARY KEY (`LAPORAN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- Dumping data for table SKRIPSIGIS.LAPORAN: ~1 rows (approximately)
/*!40000 ALTER TABLE `LAPORAN` DISABLE KEYS */;
INSERT INTO `LAPORAN` (`LAPORAN_ID`, `SISWA_ID`, `LOCATION_ID`, `LAPORAN_TANGGAL`, `LAPORAN_PENANGGUNG_JAWAB`, `LAPORAN`, `LAPORAN_STATUS`) VALUES
	(1, 8, 3, '2019-03-30', 'PENANGGUNG JAWAB', '<p>12121</p>', 'A');
/*!40000 ALTER TABLE `LAPORAN` ENABLE KEYS */;

-- Dumping structure for table SKRIPSIGIS.LOCATION
CREATE TABLE IF NOT EXISTS `LOCATION` (
  `LOCATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOCATION_USERNAME` varchar(50) NOT NULL DEFAULT '0',
  `LOCATION_PASSWORD` varchar(50) NOT NULL DEFAULT '0',
  `LOCATION_NAME` text,
  `LOCATION_LAT` text,
  `LOCATION_LNG` text,
  `LOCATION_ADDRESS` text,
  `LOCATION_KUOTA` int(11) DEFAULT NULL,
  `LOCATION_TOTAL` int(11) DEFAULT NULL,
  PRIMARY KEY (`LOCATION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- Dumping data for table SKRIPSIGIS.LOCATION: ~1 rows (approximately)
/*!40000 ALTER TABLE `LOCATION` DISABLE KEYS */;
INSERT INTO `LOCATION` (`LOCATION_ID`, `LOCATION_USERNAME`, `LOCATION_PASSWORD`, `LOCATION_NAME`, `LOCATION_LAT`, `LOCATION_LNG`, `LOCATION_ADDRESS`, `LOCATION_KUOTA`, `LOCATION_TOTAL`) VALUES
	(3, '1', '1', '1', '0.46897364515552437', '101.4415740966797', '1', 5, 2);
/*!40000 ALTER TABLE `LOCATION` ENABLE KEYS */;

-- Dumping structure for table SKRIPSIGIS.PENILAIAN
CREATE TABLE IF NOT EXISTS `PENILAIAN` (
  `PENILAIAN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SISWA_ID` int(11) NOT NULL DEFAULT '0',
  `PENILAIAN_1` varchar(50) NOT NULL DEFAULT '0',
  `PENILAIAN_2` varchar(50) NOT NULL DEFAULT '0',
  `PENILAIAN_3_KET` varchar(50) NOT NULL DEFAULT '0',
  `PENILAIAN_3` varchar(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`PENILAIAN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Dumping data for table SKRIPSIGIS.PENILAIAN: ~2 rows (approximately)
/*!40000 ALTER TABLE `PENILAIAN` DISABLE KEYS */;
INSERT INTO `PENILAIAN` (`PENILAIAN_ID`, `SISWA_ID`, `PENILAIAN_1`, `PENILAIAN_2`, `PENILAIAN_3_KET`, `PENILAIAN_3`) VALUES
	(1, 8, '2', '2', '2222', '2'),
	(2, 12, '1', '2', '4', '3');
/*!40000 ALTER TABLE `PENILAIAN` ENABLE KEYS */;

-- Dumping structure for table SKRIPSIGIS.PERMOHONAN
CREATE TABLE IF NOT EXISTS `PERMOHONAN` (
  `PERMOHONAN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SISWA_ID` int(11) DEFAULT NULL,
  `LOCATION_ID` int(11) DEFAULT NULL,
  `GURU_ID` int(11) DEFAULT NULL,
  `PERMOHONAN_STATUS` varchar(50) DEFAULT NULL,
  `PERMOHONAN_TANGGAL` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PERMOHONAN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Dumping data for table SKRIPSIGIS.PERMOHONAN: ~2 rows (approximately)
/*!40000 ALTER TABLE `PERMOHONAN` DISABLE KEYS */;
INSERT INTO `PERMOHONAN` (`PERMOHONAN_ID`, `SISWA_ID`, `LOCATION_ID`, `GURU_ID`, `PERMOHONAN_STATUS`, `PERMOHONAN_TANGGAL`) VALUES
	(1, 8, 3, 4, 'A', '2019-03-30 14:06:55'),
	(2, 12, 3, 4, 'A', '2019-04-11 11:06:51');
/*!40000 ALTER TABLE `PERMOHONAN` ENABLE KEYS */;

-- Dumping structure for table SKRIPSIGIS.SISWA
CREATE TABLE IF NOT EXISTS `SISWA` (
  `SISWA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SISWA_USERNAME` varchar(50) DEFAULT NULL,
  `SISWA_PASSWORD` varchar(50) DEFAULT NULL,
  `SISWA_NAMA` varchar(50) DEFAULT NULL,
  `SISWA_NIS` varchar(50) DEFAULT NULL,
  `SISWA_JK` varchar(50) DEFAULT NULL,
  `SISWA_TEMPAT_LAHIR` varchar(50) DEFAULT NULL,
  `SISWA_TGL_LAHIR` date DEFAULT NULL,
  `JURUSAN_ID` int(11) DEFAULT NULL,
  `NAMA_ORTU` varchar(50) DEFAULT NULL,
  `USERNAME_ORTU` varchar(50) DEFAULT NULL,
  `PASSWORD_ORTU` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`SISWA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

-- Dumping data for table SKRIPSIGIS.SISWA: ~1 rows (approximately)
/*!40000 ALTER TABLE `SISWA` DISABLE KEYS */;
INSERT INTO `SISWA` (`SISWA_ID`, `SISWA_USERNAME`, `SISWA_PASSWORD`, `SISWA_NAMA`, `SISWA_NIS`, `SISWA_JK`, `SISWA_TEMPAT_LAHIR`, `SISWA_TGL_LAHIR`, `JURUSAN_ID`, `NAMA_ORTU`, `USERNAME_ORTU`, `PASSWORD_ORTU`) VALUES
	(12, '1', '1', '1', '1', 'Laki-Laki', 'SIAK', '2019-04-18', 3, '1', '1', '1');
/*!40000 ALTER TABLE `SISWA` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
